### PR TITLE
moving from mocha to lab

### PR DESCRIPTION
**Pull request by paolochiodi**
Moved tests to lab, consistent with other stores.
This does not includes any refactoring of the tests them selves.

### CODE REVIEW

**Comment by guyellis** [comment]
@colmharte I just tested this PR and also chatted with @paolochiodi about it.

I can only get the tests to run on Node 0.10.x (tested on 0.10.40) and Seneca 0.5.x (tested on 0.5.21).

Other combinations of Node 0.12.7 and 4.0.0 and Seneca 0.6.x and 0.7.x did not work. I think that this is intended for this PR.

Changes I'd recommend to the `package.json` file:

1. I think that there should be an engines section: `"engines" : {
      "node" : ">=0.10.0 <=0.10.40"
    }`
2. We should move `seneca` to a devDependency and specify a hard version number instead of `plugin`.
3. Bump the package.json version value
4. Change `seneca-store-test` to a published version.

**Comment by paolochiodi** [comment]
@colmharte @guyellis I confirm this PR was only intended to move test framework to Lab.
Another PR is in progress for further rework, including support for new seneca and node versions.

We can add seneca and engines restrictions directly in this one if everyone agrees.

**Comment by guyellis** [comment]
My feeling is that each accepted PR should run clean on `npm test` (once the DB is setup). So I would be biased towards setting those restrictions to make that happen. We should obviously also be striving to get up to the latest in the next PR that you have pending which I think is what you're doing.

**Comment by colmharte** [comment]
@guyellis Agreed, @paolochiodi can you add the necessary restrictions to this PR ensure tests run? Then we can create a new PR to enable compatibility with latest versions of node / seneca etc

**Comment by paolochiodi** [comment]
Sure.
Should I also bump the package (minor) version?

**Comment by guyellis** [comment]
I suppose that doesn't need to be changed until we publish right?

**Comment by paolochiodi** [comment]
@guyellis Updated dependencies as agreed. Unfortunately I wasn't able to move seneca-store-test to a published version because I'm making use of some of the test that aren't in the published version.

We should ask @rjrodger to review the change and publish it in the near future

**Comment by guyellis** [comment]
LGTM. Clean `npm i` after pulling the latest and using node 0.10.40 runs clean with `npm test`.

**Pull request merged**
