### PR TITLE
fix user config

### PR DESCRIPTION
**Pull request by kamil-mech**

### CODE REVIEW

**Comment by guyellis** [comment]
How about:

`user: conf.user || conf.username`

instead of

`user: conf.user ? conf.user : conf.username`

**Comment by kamil-mech** [comment]
I was thinking the same, just wanted to keep things consistent with the
rest of your code

**Comment by guyellis** [comment]
Don't let us drag you down with our bad practices. :smile: 
Change it to what you would have originally done and I'll accept it.

**Comment by kamil-mech** [comment]
Haha :DD
It's all ready to take in

**Comment by guyellis** [comment]
@kamil-mech Do you need that published for what you're working on? Or are you referencing the master branch of this repo?

**Comment by kamil-mech** [comment]
It's alright, you can keep your current version as it is.

**Pull request merged**
